name: Inke
description: A new Flutter application.

#基于Flutter的v1.12.13-hotfixes版本 2020.5.13
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #网络图片加载
  cached_network_image: ^2.1.0+1
  #文件管理器
  path_provider: ^1.6.7
  #状态保存 flustars里自带封装了此功能
  #shared_preferences: ^0.5.7+2
  #图片选择器
  image_picker: ^0.6.5+2
  #列表下拉刷新上拉加载更多
  pull_to_refresh: ^1.5.8
  #瀑布流布局
  flutter_staggered_grid_view: ^0.3.0
  #纯Flutter版的Toast https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.3.2
  #骨架效果
  shimmer: ^1.1.1
  #Flutter的webview控件
  webview_flutter: ^0.3.21
  #android photoView
  photo_view: ^0.9.2
  #Banner轮播控件
  flutter_swiper: ^1.1.6
  #解析html标签
  flutter_html: 0.11.1
  #星形评分控件
  smooth_star_rating: ^1.0.4+2
  #点赞效果
  like_button: ^0.2.0
  #网络请求
  dio: ^2.1.0
  #系统分享
  share: ^0.6.4
  #事件总线
  event_bus: ^1.1.1
  #监听网络状态
  connectivity: ^0.4.8+4
  #将类与依赖解耦 1.注册服务 2.依赖注入
  get_it: ^4.0.2
  #状态管理 ^4.0.5+1
  provider: ^4.0.1
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.4.5
  #微信分享 https://github.com/OpenFlutter/fluwx ^1.0.3
  #fluwx: 2.0.8+3
  #Lottie在Flutter上的实现
  fluttie: ^0.5.0
  #路由管理
  fluro: ^1.6.3
  #Flutter工具类
  flustars: ^0.3.2





dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  #允许使用一组预定义的Material icons
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - assets/images/
   - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
